server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: inventory-service

management:
  tracing:
    sampling:
      probability: 1
